import { member1, member2, member3, member4, member5, member6, member7 } from "@/assets/images/images";

const members = [
    // { name: "Mr Paparao Biyyala", role: "President", img: member1 },
    // { name: "Mr D Gautam Sawang", role: "Vice President", img: member2 },
    // { name: "Dr Sarbedwar Sahraiah", role: "Vice President", img: member3 },
    // { name: "Mr Stephen Ronojit Sen", role: "Treasurer", img: member4 },
    // { name: "Prof Ajailiu Niumai", role: "General Secretary", img: member5 },
    // { name: "Dr K Rajeswara Rao", role: "Executive Committee Member", img: member6 },
    // { name: "Mr Sridhar Muppidi", role: "Executive Committee Member", img: member7 },

    {
        id: "paparao-biyyala",
        name: "Paparao Biyyala",
        role: "President",
        degustation: "IAS Officer (1982 Batch, Retired) | National Film Award Winner | Sports Administrator",
        img: member1,
        title1: "Biography",
        bio: "Papa Rao Biyyala is a distinguished former Indian Administrative Service (IAS) officer from the 1982 batch who has made remarkable contributions across multiple fields including public administration, international diplomacy, filmmaking, and sports administration.",
        title2: "Administrative Career",
        subbio: "A law graduate from Osmania University, Papa Rao Biyyala served the Indian Administrative Service with distinction for three decades. Throughout his illustrious career, he held important positions in different parts of the country and also worked with the United Nations, showcasing his expertise in governance and international relations.",
        subbio2: "He joined the Indian Administrative Service (IAS), the premier civil service of the country, in 1982. He served in many important positions, like the Deputy Commissioner of Jorhat District (1991-1993) and the Home Secretary of Assam (1994-1997).",
        subbio3: "As the Deputy Commissioner of Jorhat District, he was responsible for the overall civil administration and governance of the district with a population of about 1 million. He coordinated the police and military forces at the district level in their operations against militants by constantly monitoring them to ensure protection of human rights. In 1992, he also helped the rehabilitation of about 500 families whose houses were washed away by river erosion, with an integrated approach of providing land, house building allowance, creation of infrastructure like roads, school, water and electricity creating a new village in a record time of nine months.",
        subbio4: "While he was the Home Secretary of Assam, Mr. Rao analyzed intelligence reports of the insurgency-ridden state every day and advised the Chief Minister on policy and strategy for the prevention of outbreaks of violence and the maintenance of public order. They also implemented a statewide demobilization and rehabilitation program for the ex-combatants of the United Liberation Front of Assam (ULFA), the Bodo Liberation Tigers (BLTF), and other militant groups, which provided for the surrender of weapons and a package of training and financing for self-employment. About 10000 ex-combatants were demobilized with the surrender of weapons, and the majority of them were rehabilitated through self-employment during this period. Mr. Rao took a voluntary retirement from the Indian Administrative Service in 2005 to continue his career in peacebuilding in post-conflict areas.",
        title3: "Filmmaking Journey",
        childbio: "Driven by his passion for cinema, Papa Rao took the bold step of transitioning from civil services to filmmaking. His debut as a filmmaker earned him the prestigious National Film Award, making him one of the rare IAS officers to successfully venture into the creative arts. His notable work Music School (2023) marked his full-length feature directorial debut, which received critical acclaim for its subtle social messaging and artistic merit.",
        title4: "Sports Administration & Clean Sports India",
        subchildbio: "As the founder of 'Clean Sports India', Papa Rao has been instrumental in promoting integrity, ethics, and fairness in Indian sports. His initiative focuses on combating corruption and doping in sports, working towards creating a cleaner, more transparent sporting environment in India.",
        title5: "Awards & Recognition",
        awards: [
            "National Film Award for his debut film",
            "Recognition for distinguished service in the Indian Administrative Service",
            "Acknowledged for contributions to sports administration and clean sports advocacy"
        ],
        title6: "Legacy",
        subminbio: "Papa Rao Biyyala represents a unique blend of administrative excellence, creative vision, and social commitment. His journey from being an IAS officer to a National Award-winning filmmaker and sports administrator showcases his versatility and dedication to serving society through multiple platforms. As President of the North East Connect Association, he continues to work towards bridging communities and fostering inclusive development.",
    },
    {
        id: "gautam-sawang",
        name: "D Gautam Sawang",
        role: "Vice President",
        degustation: "IPS Officer (1986 Batch) | Former DGP Andhra Pradesh | Former APPSC Chairman",
        img: member2,
        title1: "Biography",
        title2: "Police Service Career",
        title3: "Director General of Police, Andhra Pradesh",
        title4: "Chairman, Andhra Pradesh Public Service Commission",
        title5: "Awards & Recognition",
        title6: "Contributions to Northeast Community",
        title7: "Legacy",
        bio: "Damodar Gautam Sawang is a highly decorated Indian Police Service (IPS) officer from the 1986 batch, born on July 10, 1963, in Arunachal Pradesh. He has had a distinguished career spanning over three decades in law enforcement and public administration, marked by exceptional leadership and commitment to public service.",
        subbio: "Throughout his illustrious career in the Indian Police Service, Gautam Sawang held several key positions demonstrating exemplary leadership and dedication to maintaining law and order. His service record reflects a deep commitment to community policing, modernization of police forces, and upholding the highest standards of professional integrity.",
        childbio: "Gautam Sawang served as the Director General of Police (DGP) for Andhra Pradesh from May 2019 to February 2022. During his tenure as DGP, he implemented several progressive policing reforms and initiatives aimed at improving law enforcement efficiency and public safety. He resigned from the position in February 2022, two years prior to his scheduled retirement, marking the end of a distinguished career at the helm of the state's police force.",
        subchildbio: "Following his tenure as DGP, Gautam Sawang was appointed as the Chairman of the Andhra Pradesh Public Service Commission (APPSC) in February 2022. In this role, he oversaw the recruitment and selection processes for various government positions in Andhra Pradesh, ensuring transparency and merit-based selection. He served in this capacity until his resignation in 2024, continuing his commitment to public service and governance.",
        awards: [
            "President's Police Medal for Distinguished Service",
            "Recognition for outstanding leadership as DGP, Andhra Pradesh",
            "Commendations for modernizing police systems and community policing initiatives"
        ],
        subminbio: "As Vice President of the North East Connect Association, Gautam Sawang leverages his extensive administrative experience and leadership skills to support and empower the Northeast community in Hyderabad and Telangana. His understanding of governance and public administration makes him an invaluable asset in addressing community needs and fostering inclusive development.",
        lowsubbio: "Gautam Sawang's career exemplifies dedication, integrity, and progressive leadership in public service. From his roots in Arunachal Pradesh to leading one of India's largest state police forces, his journey reflects his commitment to excellence and service to society. His continued involvement in community development through the North East Connect Association demonstrates his ongoing commitment to social welfare and community empowerment."
    },
    {
        id: "sarbedwar-sahraiah",
        name: "Dr Sarbeswar Sahraiah",
        role: "Vice President",
        degustation: "Padma Shri Awardee | Chief Transplant Surgeon | Pro Vice Chancellor, USTM",
        img: member3,
        title1: "Biography",
        bio: "Dr. Sarbeswar Sahariah, born on April 1, 1945, in Mangaldai, Darrang, Assam, is one of India's most accomplished organ transplant surgeons and nephrologists. His pioneering work in kidney transplantation has saved thousands of lives and established him as a legendary figure in Indian medical history.",
        title2: "Medical Excellence & Pioneering Work",
        subbio: "Dr. Sahariah's medical career is marked by extraordinary achievements and firsts in the field of organ transplantation. He performed Hyderabad's first kidney transplant in 1981, opening new frontiers in medical treatment in the region. Over his illustrious career, he has successfully performed over 3,000 kidney transplants, earning him recognition as one of India's most experienced transplant surgeons.",
        subbio2: "He holds the qualifications of MS, MAMS, FICS, and FACS, and has served as Chief Transplant Surgeon and Urologist at prestigious hospitals including KIMS Hospital in Hyderabad and Mahavir Hospital. His expertise and skill have made him a sought-after surgeon for complex transplant cases.",
        title3: "North East Care Foundation",
        childbio: "Recognizing the healthcare disparities in Northeast India, Dr. Sahariah founded the North East Care Foundation to provide medical care and support to underserved communities in the region. This initiative reflects his deep commitment to giving back to his roots and ensuring that quality healthcare reaches those who need it most, regardless of their geographic or economic circumstances.",
        title4: "Academic Leadership at USTM",
        subchildbio: "In 2024, Dr. Sahariah joined the University of Science and Technology Meghalaya (USTM) as Pro Vice Chancellor. In this role, he also contributes to the P A Sangma International Medical College and Hospital, Meghalaya, bringing his vast experience and expertise to shape the next generation of medical professionals. His appointment to this prestigious position underscores his continued commitment to medical education and healthcare advancement in Northeast India.",
        title5: "Awards & Recognition",
        awards: [
            "Padma Shri (2014): India's fourth-highest civilian award, recognizing his exceptional contributions to medicine",
            "Brahmaiah Sastry Memorial Oration Award: For outstanding contributions to urology and transplant surgery",
            "Multiple recognitions from national and international medical organizations",
            "Honorary positions at leading medical institutions across India"
        ],
        title6: "Community Service & Northeast Connect",
        subminbio: "As Vice President of the North East Connect Association, Dr. Sahariah continues his lifelong mission of serving the Northeast community. He brings his experience, networks, and deep understanding of community needs to help address healthcare challenges and support the welfare of people from Northeast India living in Telangana and beyond. His involvement adds tremendous credibility and support to the association's healthcare initiatives.",
        title7: "Legacy",
        lowsubbio: "Dr. Sarbeswar Sahariah's legacy extends far beyond the thousands of lives he has directly saved through his surgical skills. He has inspired countless medical professionals, pioneered transplant surgery in Hyderabad, and demonstrated an unwavering commitment to serving underserved communities. His work with the North East Care Foundation and his leadership at USTM continue to impact healthcare delivery and medical education in Northeast India. At nearly 80 years of age, he remains active in medical practice, education, and community service, embodying the spirit of lifelong dedication to healing and service."

    },
    {
        id: "ajailiu-niumai",
        name: "Prof Ajailiu Niumai",
        role: "General Secretary",
        degustation: "Professor of Sociology | University of Hyderabad | Social Inclusion Expert",
        img: member5,
        title1: "Biography",
        bio: "Professor Ajailiu (Ajai) Niumai is a distinguished Professor of Sociology at the University of Hyderabad and a leading scholar in the fields of gender studies, Northeast India studies, migration and Indian diaspora studies, and tribal studies. Her pioneering research and advocacy have significantly contributed to understanding and addressing social exclusion and promoting inclusive policies in India.",
        title2: "Academic Career",
        subbio: "Professor Niumai joined the University of Hyderabad as Assistant Professor in the Department of Sociology in 2000 and rose through the ranks to become a full Professor. Her academic journey reflects a deep commitment to understanding marginalized communities and advocating for their rights through rigorous scholarship and engaged research.",
        subbio2: "She served as the former Head of the Centre for the Study of Social Exclusion & Inclusive Policy at the University of Hyderabad, where she led groundbreaking research on social inclusion, equity, and justice. Under her leadership, the centre became a leading hub for research on marginalized communities and inclusive development policies.",
        title3: "Pioneer in Women's Studies",
        childbio: "In 2007, Professor Niumai was one of the pioneers in establishing the Centre for Women's Studies at the University of Hyderabad. This initiative created an institutional space for feminist scholarship and gender-focused research, contributing to the advancement of women's rights and gender equality in academic discourse and policy formulation.",
        title4: "Research Specializations",
        subinfo: [
            {
                subtitle: "Gender Studies",
                subdata: "Her research on gender focuses on understanding power structures, discrimination, and pathways to achieving gender equality, particularly in the context of marginalized communities.",
            },
            {
                subtitle: "Northeast India Studies",
                subdata: "Professor Niumai is a leading authority on Northeast India, examining the region's unique social, cultural, and political dynamics, including issues of identity, autonomy, and development.",
            },
            {
                subtitle: "Migration & Indian Diaspora Studies",
                subdata: "Her work on migration explores the experiences of displaced communities, diaspora identities, and the challenges faced by migrants in adapting to new environments while maintaining cultural ties.",
            },
            {
                subtitle: "Tribal Studies",
                subdata: "Her research on tribal communities examines their socio-economic conditions, cultural practices, and struggles for rights and recognition in contemporary India.",
            }
        ],
        title6: "International Collaborations",
        subminbio: "Professor Niumai has engaged in international academic collaborations, including serving as Senior Research Associate at the Department of Sociology, University of Johannesburg, South Africa. She has also been a CARTHA Fellow and has presented at numerous international conferences, including the South Asia Studies conference in Madison, Wisconsin.",
        subminbio2: "She holds the position of Honorary Adjunct Professor at the Department of Science and Humanities, National Institute of Technology (NIT), Nagaland, further extending her influence in shaping higher education and research in Northeast India.",
        title7: "Current Focus: Manipur Conflict",
        lowsubbio: "In recent years, Professor Niumai has been actively engaged in understanding and providing insights on the ongoing conflict in Manipur. Her sociological analysis of the ethnic tensions and the struggle for peace in Northeast India has contributed to broader conversations about conflict resolution and community reconciliation. Her work in this area has been featured in international forums, including presentations at the University of Iowa.",
        title8: "Role in North East Connect Association",
        lowsubbio4: "As Secretary of the North East Connect Association, Professor Niumai brings her extensive academic expertise, research networks, and deep understanding of Northeast communities to the organization. Her insights into social inclusion, migration experiences, and community development inform the association's programs and advocacy efforts. Her role is crucial in ensuring that the association's work is grounded in evidence-based approaches and addresses the real needs of the Northeast community in Telangana.",
        title9: "Legacy",
        lowsubbio3: "Professor Ajailiu Niumai stands as a leading voice for marginalized communities, particularly those from Northeast India. Through her scholarship, teaching, and community engagement, she has contributed significantly to advancing social justice, gender equality, and inclusive development. Her work continues to inspire students, researchers, and activists working towards a more equitable society. As Secretary of the North East Connect Association, she ensures that academic rigor and community needs come together to create meaningful impact."
    },
    {
        id: "stephen-ronojit",
        name: "Stephen Ronojit Sen",
        role: "Treasurer",
        degustation: "Senior Lawyer | Director, Hand of Hope Legal Services | Legal Rights Advocate",
        img: member4,
        title1: "Biography",
        bio: "Stephen Sen is a seasoned lawyer based in Hyderabad with extensive experience in legal practice and advocacy. As Director of Hand of Hope Legal Services, he has dedicated his career to providing legal assistance and ensuring access to justice for individuals and communities. His commitment to legal excellence and social justice makes him an invaluable asset to the North East Connect Association.",
        title2: "Education",
        subbio: "Stephen Sen's academic journey reflects his intellectual rigor and commitment to excellence. He graduated from the prestigious St. Stephen's College, Delhi (1994-1997), one of India's premier institutions known for producing distinguished scholars, leaders, and professionals. Following his undergraduate studies in Arts, he pursued legal education at Osmania University, Hyderabad, where he obtained both his Bachelor of Laws (LLB) and Master of Laws (LLM) degrees.",
        subbio2: "This strong educational foundation from two of India's most respected institutions equipped him with both theoretical knowledge and practical understanding of law, enabling him to navigate complex legal challenges and advocate effectively for his clients.",
        title3: "Professional Practice",
        childbio: "As a practicing lawyer in Hyderabad, Stephen Sen has built a reputation for his expertise across various areas of law. His practice encompasses civil law, constitutional matters, human rights advocacy, and legal counseling. He is known for his meticulous approach to legal research, persuasive advocacy, and commitment to upholding the rule of law.",
        childbio2: "His experience in handling diverse legal matters has given him insights into the legal challenges faced by different communities, including marginalized groups. This understanding is particularly relevant to his work with the North East Connect Association, where legal literacy and access to justice are important components of community empowerment.",
        title4: "Hand of Hope Legal Services",
        subchildbio: "As Director of Hand of Hope Legal Services, Stephen Sen leads an organization committed to providing legal assistance and support to those in need. The organization focuses on ensuring that legal services are accessible to all, particularly those who may face barriers due to economic, social, or cultural factors. Under his leadership, Hand of Hope Legal Services has helped numerous individuals navigate the legal system and secure their rights.",
        subchildbio2: "The organization's work includes legal aid, rights awareness programs, assistance with documentation, and advocacy for systemic changes to improve access to justice. This mission aligns closely with the goals of the North East Connect Association, particularly in helping community members understand and access their legal rights and entitlements.",
        title5: "Role as Treasurer",
        minsubbio: "As Treasurer of the North East Connect Association, Stephen Sen brings his organizational skills, attention to detail, and commitment to transparency to manage the association's financial affairs. His legal background ensures that all financial operations comply with regulatory requirements and best practices in non-profit governance.",
        minsubbio2: "Beyond financial management, his role as Treasurer also involves strategic planning for resource mobilization, ensuring efficient use of funds to maximize impact on the community, and maintaining accountability to members and donors. His experience in organizational management through Hand of Hope Legal Services makes him well-suited for this responsibility.",
        title6: "Commitment to Northeast Community",
        subminbio: "Stephen Sen's connection to the Northeast community and his understanding of the legal and social challenges they face inform his work with the North East Connect Association. He is particularly focused on ensuring that community members have access to legal information and assistance, whether related to property matters, employment issues, documentation, or other legal concerns.",
        subminbio2: "His legal expertise is invaluable in addressing situations where community members may face discrimination or require legal support. He actively works to build bridges between the legal system and the Northeast community, making the often-complex legal processes more accessible and understandable.",
        title7: "Vision & Contributions",
        lowsubbio: "Stephen Sen envisions a society where legal services and justice are accessible to all, regardless of their background or economic status. Through his work with the North East Connect Association, he contributes to creating a support system for the Northeast community in Hyderabad and Telangana, ensuring they have the resources and knowledge to protect their rights and participate fully in society.",
        lowsubbio2: "His dual role as a legal professional and community leader exemplifies the spirit of service that drives the North East Connect Association. His contributions in financial stewardship, legal guidance, and community advocacy are instrumental in the association's efforts to create a stronger, more empowered Northeast community.",
    },
    {
        id: "rajeswara-rao",
        name: "Dr K Rajeswara Rao",
        role: "Senior Retired IAS Officer",
        degustation: "IAS (1988 Batch) | Former Special Secretary, NITI Aayog | President, Sampark Foundation",
        img: member6,
        title1: "Biography",
        bio: "Dr. K. Rajeswara Rao is a distinguished retired Indian Administrative Service (IAS) officer from the 1988 batch with a career spanning over three decades as an administrative and development professional. His extensive experience in governance, policy formulation, and implementation at the highest levels of government has positioned him as a leading expert in urban development, skill development, and social sector reforms.",
        title2: "Ministerial Experience",
        subbio: "Throughout his 34-year administrative career, Dr. Rao worked across six major ministries of the Government of India for approximately 16 years, gaining diverse experience and deep expertise in multiple sectors:",
        minstylist: [
            "Ministry of Mines : Contributing to policy development in India's mining sector",
            "Ministry of Health : Working on healthcare policies and programs",
            "Ministry of Railways : Involvement in railway development and modernization initiatives",
            "Ministry of Food Processing : Supporting agricultural value addition and food industry development",
            "Ministry of Women and Child Welfare: Advancing policies for women's empowerment and child welfare",
        ],
        subbio2: "He worked at various levels within these ministries—as Director, Joint Secretary, Additional Secretary, and Special Secretary—gaining comprehensive understanding of policy formulation, inter-ministerial coordination, and program implementation at scale.",
        title3: "Special Secretary at NITI Aayog",
        childbio: "Dr. Rao's most prominent role was serving as Special Secretary (in the rank of Secretary to Government of India) at NITI Aayog, India's premier policy think tank. In this capacity, he was in charge of two critical portfolios:",
        special: [
            {
                subtitle: "Urban Development",
                subdata: "He played a key role in shaping India's urban development agenda, working on policies and programs to address rapid urbanization challenges, improve urban infrastructure, and enhance quality of life in cities. His work contributed to major urban missions and initiatives aimed at making Indian cities more livable, sustainable, and economically vibrant.",
            },
            {
                subtitle: "Skill Development",
                subdata: "Recognizing that skill development is crucial for India's demographic dividend, Dr. Rao led efforts to strengthen skill training infrastructure, align skill development programs with industry needs, and create pathways for youth employment. His work in this area has had significant impact on enhancing employability of millions of Indian youth.",
            },
        ],
        title4: "President, Sampark Foundation",
        subchildbio: "In November 2022, following his retirement from government service, Dr. Rajeswara Rao joined Sampark Foundation as its President. Sampark Foundation is a leading NGO founded by Anupama and Vineet Nayar with a mission to deliver large-scale improvement in learning outcomes for 2 crore (20 million) government school children across India.",
        subchildbio2: "In this role, Dr. Rao works closely with the foundation's founders to transform government school education at scale. His experience in government policy-making and program implementation is invaluable in designing interventions that can work within the government system and achieve sustainable impact. The foundation's focus on improving learning outcomes for government school children aligns with his lifelong commitment to social sector development and inclusive growth.",
        title5: "Development Philosophy & Approach",
        minsubbio: "Dr. Rao is known for his pragmatic, evidence-based approach to development policy. His extensive experience across multiple ministries has given him a holistic understanding of development challenges and the interconnections between different sectors. He advocates for:",
        awards: [
            "Data-driven policy formulation and monitoring",
            "Collaborative approaches involving government, private sector, and civil society",
            "Focus on implementation and last-mile delivery",
            "Capacity building at state and local government levels",
            "Sustainable and inclusive development that benefits all sections of society"
        ],
        title6: "Contributions to Policy Discourse",
        subminbio: "Dr. Rao has contributed to policy discourse through various platforms including Ideas for India, where he has shared insights on urban development, skill training, and governance reforms. He is a sought-after speaker at academic institutions, policy conferences, and development forums, where he shares his experiences and perspectives on making government programs more effective.",
        title7: "Role in North East Connect Association",
        lowsubbio: "As a founding member of the North East Connect Association, Dr. Rajeswara Rao brings his vast administrative experience, policy expertise, and networks in government and development sectors. His understanding of government programs, skill development initiatives, and social welfare schemes is invaluable in helping the association navigate government systems and access resources for community development.",
        lowsubbio2: "His involvement in the association also helps bridge the gap between the Northeast community and government institutions, ensuring that the community's needs and aspirations are effectively represented and addressed in policy discussions and development initiatives. His role is crucial in guiding the association's strategic direction and maximizing its impact on the Northeast community in Telangana.",
        title8: "Legacy & Vision",
        lowsubbio4: "Dr. K. Rajeswara Rao's career exemplifies dedicated public service and commitment to inclusive development. From working on national policies at NITI Aayog to grassroots-level education reform with Sampark Foundation, and community empowerment through the North East Connect Association, his work consistently focuses on creating opportunities for marginalized sections of society.",
        lowsubbio5: "His vision is of an India where every child receives quality education, every youth has employable skills, cities are livable and sustainable, and no community is left behind in the development journey. Through his continued work in the social sector post-retirement, he demonstrates that public service is not just a career but a lifelong commitment to nation-building and social transformation.",
    },
    {
        id: "sridhar-muppidi",
        name: "Mr Sridhar Muppidi",
        role: "Entrepreneur & Gaming Industry",
        degustation: "CEO & Co-Founder, YesGnome | President, India Game Developer Conference",
        img: member7,
        title1: "Biography",
        bio: "Sridhar Muppidi is a successful entrepreneur with a strong background in the technology and gaming industries. Based in Hyderabad, he has been instrumental in establishing India as a significant player in the global gaming ecosystem. His journey from technology professional to gaming industry leader and social entrepreneur exemplifies innovation, leadership, and commitment to community development.",
        title2: "YesGnome: Creating Captivating Gaming Experiences",
        subbio: "As CEO and Co-Founder of YesGnome, Sridhar has led the company in creating captivating mobile games that have reached millions of players worldwide. YesGnome, based in Hyderabad, is renowned for its vibrant and engaging gaming experiences that combine innovative gameplay, compelling narratives, and high-quality production values.",
        subbio2: "Under his leadership, YesGnome has developed a portfolio of successful mobile games that have received critical acclaim and commercial success. The company's philosophy centers on creating games that people love to play, with a focus on user experience, creativity, and technical excellence. Sridhar's extensive expertise in game development has been instrumental in driving YesGnome's growth and establishing its reputation in the competitive gaming industry.",
        title3: "President, India Game Developer Conference (IGDC)",
        childbio: "Sridhar Muppidi serves as President of the India Game Developer Conference (IGDC), the country's premier event for game creators, studios, and industry professionals. IGDC, which began as a NASSCOM initiative in the early 2000s, has evolved into the longest-running and largest game developer conference in India and one of Asia's leading events for game developers.",
        childbio2: "Under his leadership, IGDC has transformed into a fully industry-led platform—run by volunteers, powered by passion, and dedicated to advancing India's place in the global gaming industry. What started as a modest meet-up in Hyderabad has grown to attract thousands of developers, industry leaders, and gaming enthusiasts from across India and around the world. His vision and dedication have been crucial in making IGDC a launchpad for aspiring game developers and a networking hub for established professionals.",
        title4: "The Volunteer Movement",
        subchildbio: "One of Sridhar's most significant contributions to the gaming industry has been fostering a volunteer-driven movement that powers IGDC. The conference is organized and run by passionate volunteers from the gaming community who donate their time and expertise to make the event successful. This community-first approach has created a strong sense of ownership and belonging among Indian game developers, turning IGDC into more than just a conference—it's a movement that celebrates and nurtures Indian gaming talent.",
        title5: "EducationForFree.org: Commitment to Social Causes",
        minsubbio: "Beyond his commercial success in gaming, Sridhar is the founder of educationforfree.org, demonstrating his deep commitment to social causes and educational equity. This initiative focuses on providing free educational resources and opportunities to underprivileged students, helping bridge the digital divide and democratize access to quality education.",
        minsubbio2: "Through educationforfree.org, Sridhar leverages technology to create scalable solutions for educational challenges, ensuring that economic barriers don't prevent talented individuals from accessing learning opportunities. This work reflects his belief that education is a fundamental right and a powerful tool for social transformation.",
        title6: "Impact on Indian Gaming Industry",
        subminbio: "Sridhar's contributions have significantly impacted India's gaming ecosystem. Through YesGnome, he has created jobs, mentored young developers, and demonstrated that world-class games can be created from India. Through IGDC, he has provided a platform for thousands of developers to learn, network, and grow their careers. His work has helped establish Hyderabad as a major hub for game development in India.",
        subminbio2: "His leadership has inspired a generation of Indian game developers to pursue their creative visions and compete on the global stage. The success stories of many developers who got their start or made crucial connections at IGDC are a testament to the ecosystem he has helped build.",
        title7: "Role in North East Connect Association",
        lowsubbio: "As a founding member of the North East Connect Association, Sridhar brings his entrepreneurial acumen, technology expertise, and social commitment to support the Northeast community in Hyderabad and Telangana. His experience in building communities around IGDC informs his approach to community development with the association.",
        lowsubbio2: "His involvement helps the association explore opportunities in technology, gaming, and digital media for Northeast youth, potentially creating pathways for them to enter these growing industries. His commitment to education through educationforfree.org also aligns with the association's goals of empowering the community through skill development and education.",
        title8: "Vision & Legacy",
        lowsubbio4: "Sridhar Muppidi's journey from technology professional to gaming industry leader and social entrepreneur embodies the spirit of innovation, community building, and social responsibility. His work demonstrates that business success and social impact can go hand in hand. Through YesGnome, he creates entertainment and employment; through IGDC, he nurtures an industry and community; and through educationforfree.org and the North East Connect Association, he works to create opportunities for underserved communities.",
        lowsubbio5: "His vision of a vibrant, inclusive gaming industry in India that provides opportunities for talented individuals regardless of their background continues to drive his work. As the gaming industry grows, Sridhar's contributions to building its foundations and ensuring it remains accessible and inclusive will remain his lasting legacy."
    }
];




export default members;